AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*

  Include:
    - '**/*.builder'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Vagrantfile'

  DisplayCopNames: true

  DisplayStyleGuide: true

#
# @todo: Decide on a better default than 25 and reenable. 25 is science-fiction
# for a Rails app, specially if it uses gems like activeadmin.
#
Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 110

Performance/Casecmp:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/EmptyMethod:
  EnforcedStyle: expanded

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test

inherit_from: .rubocop_todo.yml
