---

language: ruby

sudo: required

dist: trusty

cache:
  bundler: true
  apt: true

services:
  - redis-server

rvm:
  - 2.3.1

before_install:
  - gem update --system
  - gem install bundler
  - sudo apt-get update

script:
  - RAILS_ENV=test bin/rake db:drop db:create db:schema:load
  - bin/rake download_maxmind_db
  - bin/rake

before_script:
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.yml.example config/database.yml

branches:
  only:
    - master

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
