version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      # For deploy with capistrano, pass the .ssh/config and ssh-agent
      - ~/.ssh:/root/.ssh
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - SSH_AUTH_SOCK=/ssh-agent
    ports:
      - 3000:9292
    links:
      - pg
    command: bundle exec puma
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
